var days=[['lunedi','Lun'],['martedi','Mar'],['mercoledi','Mer'],['giovedi','Gio'],['venerdi','Ven'],['sabato','Sab'],['domenica','Dom']];
var departments=[
  {key:'sala',title:'Sala',people:['Pawel','Rafaele','Gaetano','Rose','Shan','Brendon','Vittorio','Dylan','Lorenzo','Sabbit','Annachiara','Natalia','Carmine'],values:['Riposo','A','P','S','A/S','P/S','10','12','15:30','16','17','19']},
  {key:'pizzeria',title:'Pizzeria',people:['LUCA','MARIO','IGOR','CRISTIAN','PIETRO'],values:['Riposo','M','S','M/S','12/chius']},
  {key:'cucina',title:'Cucina / Lavaggio',people:['ANTONINO','Lavapiatti','AJITH','DIEGO','Saja'],values:['Riposo','M','S','M/S','12/chius']}
];
var storeName='capriBluAppTurniByWeekV1';var weekStoreName='capriBluAppCurrentWeekV1';var requestStoreName='capriBluAppRequestsV1';var departmentStateStoreName='capriBluAppDepartmentOpenV1';var allData={};var requests=[];var departmentOpenState={};var activeCell=null;
try{allData=JSON.parse(localStorage.getItem(storeName)||'{}')}catch(e){allData={}}
try{requests=JSON.parse(localStorage.getItem(requestStoreName)||'[]')}catch(e){requests=[]}
try{departmentOpenState=JSON.parse(localStorage.getItem(departmentStateStoreName)||'{}')}catch(e){departmentOpenState={}}
function markLocalChanges(text){var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(official){official.textContent='Modifiche locali';official.classList.add('is-dirty')}if(save){save.textContent=text||'Salvato locale';save.classList.add('is-dirty')}}
window.markLocalChanges=markLocalChanges;
function currentWeek(){var input=document.getElementById('weekInput');var mobile=document.getElementById('mobileWeekInput');return input&&input.value?input.value:(mobile&&mobile.value?mobile.value:'no-week')}
function weekData(){var key=currentWeek();if(!allData[key])allData[key]={};return allData[key]}
function cellKey(dep,person,day){return dep+'_'+person+'_'+day}
function cellValue(dep,person,day){return weekData()[cellKey(dep,person,day)]||'Riposo'}
function saveAll(){localStorage.setItem(storeName,JSON.stringify(allData));localStorage.setItem(weekStoreName,currentWeek())}
function saveCell(dep,person,day,value){weekData()[cellKey(dep,person,day)]=value;saveAll();markLocalChanges('Salvato locale '+currentWeek())}
function depByKey(key){return departments.find(function(dep){return dep.key===key})}
function isDepartmentOpen(key){return departmentOpenState[key]!==false}
function saveDepartmentState(){localStorage.setItem(departmentStateStoreName,JSON.stringify(departmentOpenState))}
function thisWeek(){var d=new Date();var day=d.getDay()||7;d.setDate(d.getDate()+4-day);var y=new Date(d.getFullYear(),0,1);var w=Math.ceil((((d-y)/86400000)+1)/7);return d.getFullYear()+'-W'+String(w).padStart(2,'0')}
function previousWeek(value){var parts=value.split('-W');var year=Number(parts[0]);var week=Number(parts[1]);week=week-1;if(week<1){year=year-1;week=52}return year+'-W'+String(week).padStart(2,'0')}
function setupWeek(){var input=document.getElementById('weekInput');var mobile=document.getElementById('mobileWeekInput');if(!input)return;var saved=localStorage.getItem(weekStoreName)||thisWeek();input.value=saved;if(mobile)mobile.value=saved;updateWeekLabel();input.addEventListener('change',function(){if(mobile)mobile.value=input.value;localStorage.setItem(weekStoreName,input.value);updateWeekLabel();renderSchedule()});if(mobile)mobile.addEventListener('change',function(){input.value=mobile.value;localStorage.setItem(weekStoreName,mobile.value);updateWeekLabel();renderSchedule();if(typeof updateMenuWeekLabel==='function')updateMenuWeekLabel()})}
function shortItalianDate(value){if(!value)return'';var p=value.split('-');return p[2]+'/'+p[1]+'/'+p[0]}
function updateWeekLabel(){var label=document.getElementById('weekRange');var mobileLabel=document.getElementById('mobileWeekRange');var week=currentWeek();var text='-';if(week&&week!=='no-week')text=shortItalianDate(dateForWeekDay(week,'lunedi'))+' - '+shortItalianDate(dateForWeekDay(week,'domenica'));if(label)label.textContent=text;if(mobileLabel)mobileLabel.textContent=text}
function formatDate(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dateForWeekDay(weekValue,dayKey){var index=days.findIndex(function(day){return day[0]===dayKey});if(index<0||weekValue==='no-week')return '';var parts=weekValue.split('-W');var year=Number(parts[0]);var week=Number(parts[1]);var jan4=new Date(year,0,4);var jan4Day=jan4.getDay()||7;var monday=new Date(year,0,4-jan4Day+1);monday.setDate(monday.getDate()+(week-1)*7+index);return formatDate(monday)}
function requestFor(person,dayKey){var date=dateForWeekDay(currentWeek(),dayKey);return requests.find(function(item){return item.person===person&&item.date===date&&(item.status==='approvata'||item.status==='in attesa'||item.status==='pending')})}
function requestVisualClass(item){if(!item)return'';if(item.status==='approvata')return' has-approved-request';return' has-pending-request'}
function renderSchedule(){var root=document.getElementById('scheduleSections');if(!root)return;root.innerHTML='';departments.forEach(function(dep){var open=isDepartmentOpen(dep.key);var card=document.createElement('div');card.className='department-card'+(open?'':' is-collapsed');var html='<button class="department-title" type="button" data-dep-toggle="'+dep.key+'" aria-expanded="'+open+'">'+dep.title+'</button>';dep.people.forEach(function(person){html+='<div class="employee-row"><div class="employee-name">'+person+'</div><div class="days-grid">';days.forEach(function(day){var req=requestFor(person,day[0]);var badge=req?'<span class="request-badge '+(req.status==='approvata'?'approved':'pending')+'">'+(req.status==='approvata'?'Approvata':'In attesa')+': '+req.type+'</span>':'';html+='<button class="shift-btn'+requestVisualClass(req)+'" type="button" data-dep="'+dep.key+'" data-person="'+person+'" data-day="'+day[0]+'"><span class="shift-day">'+day[1]+'</span><span class="shift-value">'+cellValue(dep.key,person,day[0])+'</span>'+badge+'</button>'});html+='</div></div>'});card.innerHTML=html;root.appendChild(card)})}
function setupTabs(){document.querySelectorAll('.tab-btn').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.tab-btn').forEach(function(item){item.classList.remove('active')});document.querySelectorAll('.view').forEach(function(view){view.classList.remove('active-view')});btn.classList.add('active');var view=document.getElementById(btn.dataset.view+'View');if(view){view.classList.add('active-view')}})})}
function setupDepartmentToggles(){var root=document.getElementById('scheduleSections');if(!root)return;root.addEventListener('click',function(event){var title=event.target.closest('.department-title');if(!title)return;var card=title.closest('.department-card');var key=title.dataset.depToggle;var collapsed=card.classList.toggle('is-collapsed');title.setAttribute('aria-expanded',String(!collapsed));departmentOpenState[key]=!collapsed;saveDepartmentState()})}
function shiftButtonClass(value){var v=String(value).toLowerCase();if(v==='riposo'||v==='off')return ' is-rest-option';if(v.indexOf('/')>-1||v.indexOf(':')>-1||v.indexOf('cena')>-1||v.indexOf('pranzo')>-1)return ' is-special-option';return ''}
function applyShift(value){if(!activeCell)return;activeCell.querySelector('.shift-value').textContent=value;saveCell(activeCell.dataset.dep,activeCell.dataset.person,activeCell.dataset.day,value);closeShiftEditor()}
function openShiftEditor(cell){activeCell=cell;var dep=depByKey(cell.dataset.dep);if(!dep)return;var editor=document.getElementById('shiftEditor');var title=document.getElementById('shiftEditorTitle');var options=document.getElementById('shiftOptions');var custom=document.getElementById('customShiftInput');title.textContent=dep.title+' · '+cell.dataset.person+' · '+cell.dataset.day;options.innerHTML='';dep.values.forEach(function(value){var btn=document.createElement('button');btn.className='shift-option-btn'+shiftButtonClass(value);btn.type='button';btn.textContent=value;btn.addEventListener('click',function(){applyShift(value)});options.appendChild(btn)});custom.value=cell.querySelector('.shift-value').textContent;editor.classList.add('open');editor.setAttribute('aria-hidden','false')}
function closeShiftEditor(){var editor=document.getElementById('shiftEditor');editor.classList.remove('open');editor.setAttribute('aria-hidden','true');activeCell=null}
function setupShiftEditor(){var close=document.getElementById('closeShiftEditorBtn');var save=document.getElementById('saveCustomShiftBtn');var clear=document.getElementById('clearShiftBtn');var editor=document.getElementById('shiftEditor');if(close)close.addEventListener('click',closeShiftEditor);if(save)save.addEventListener('click',function(){var input=document.getElementById('customShiftInput');applyShift((input.value||'Riposo').trim()||'Riposo')});if(clear)clear.addEventListener('click',function(){applyShift('Riposo')});if(editor)editor.addEventListener('click',function(event){if(event.target===editor)closeShiftEditor()})}
function setupCellTap(){var root=document.getElementById('scheduleSections');if(!root)return;root.addEventListener('click',function(event){var cell=event.target.closest('.shift-btn');if(!cell)return;openShiftEditor(cell)})}
function copyPreviousWeekAction(){var current=currentWeek();var previous=previousWeek(current);if(!allData[previous]){alert('Nessun turno trovato nella settimana '+previous);return}if(!confirm('Copiare i turni da '+previous+' a '+current+'?'))return;allData[current]=JSON.parse(JSON.stringify(allData[previous]));saveAll();renderSchedule();markLocalChanges('Copiata '+previous)}
function setupCopyPreviousWeek(){var btn=document.getElementById('copyPreviousWeekBtn');if(btn)btn.addEventListener('click',copyPreviousWeekAction)}
window.copyPreviousWeekAction=copyPreviousWeekAction;
function saveRequests(){localStorage.setItem(requestStoreName,JSON.stringify(requests));markLocalChanges('Richieste salvate')}
function setupRequestPeople(){var select=document.getElementById('requestPerson');if(!select)return;var names=[];departments.forEach(function(dep){dep.people.forEach(function(name){if(names.indexOf(name)<0)names.push(name)})});select.innerHTML=names.map(function(name){return '<option>'+name+'</option>'}).join('')}
function sendApprovalEmail(item){if(!item.email)return;var subject='Richiesta approvata - Capri Blu Sorrento';var body='Ciao '+item.person+',\n\nla tua richiesta è stata approvata.\n\nTipo: '+item.type+'\nGiorno: '+item.date+'\n\nCapri Blu Sorrento';window.location.href='mailto:'+item.email+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)}
function renderRequests(){var list=document.getElementById('requestsList');if(!list)return;if(!requests.length){list.innerHTML='<div class="panel-card">Nessuna richiesta salvata.</div>';return}list.innerHTML='';requests.slice().reverse().forEach(function(item){var card=document.createElement('div');card.className='request-card '+(item.status==='approvata'?'is-approved':'is-pending');card.innerHTML='<strong>'+item.person+' - '+item.type+'</strong><div class="request-meta">'+item.date+' - '+item.status+(item.email?' - '+item.email:'')+'</div><p class="request-note">'+(item.note||'')+'</p><div class="request-actions"><button class="mini-btn" type="button" data-action="approve" data-id="'+item.id+'">Approva</button><button class="mini-btn" type="button" data-action="reject" data-id="'+item.id+'">Rifiuta</button><button class="mini-btn" type="button" data-action="remove" data-id="'+item.id+'">Rimuovi</button></div>';list.appendChild(card)})}
function updateRequestStatus(id,status){var approvedItem=null;requests=requests.map(function(item){if(String(item.id)===String(id)){item.status=status;if(status==='approvata')approvedItem=item}return item});saveRequests();renderRequests();renderSchedule();if(approvedItem)sendApprovalEmail(approvedItem)}
function removeRequest(id){requests=requests.filter(function(item){return String(item.id)!==String(id)});saveRequests();renderRequests();renderSchedule()}
function setupRequests(){setupRequestPeople();renderRequests();var add=document.getElementById('addRequestBtn');var list=document.getElementById('requestsList');if(add)add.addEventListener('click',function(){var person=document.getElementById('requestPerson').value;var type=document.getElementById('requestType').value;var date=document.getElementById('requestDate').value||'-';var note=document.getElementById('requestNote').value.trim();requests.push({id:Date.now(),person:person,type:type,date:date,note:note,status:'in attesa'});document.getElementById('requestNote').value='';saveRequests();renderRequests();renderSchedule()});if(list)list.addEventListener('click',function(event){var btn=event.target.closest('.mini-btn');if(!btn)return;if(btn.dataset.action==='approve')updateRequestStatus(btn.dataset.id,'approvata');if(btn.dataset.action==='reject')updateRequestStatus(btn.dataset.id,'rifiutata');if(btn.dataset.action==='remove')removeRequest(btn.dataset.id)})}
setupTabs();setupWeek();renderSchedule();setupDepartmentToggles();setupCellTap();setupShiftEditor();setupCopyPreviousWeek();setupRequests();
