var archiveSelectedMonthStoreName='capriBluAppArchiveSelectedMonthV1';
var archiveModeStoreName='capriBluAppArchiveModeV1';
var publishedWeeksStoreName='capriBluAppPublishedMonthlyWeeksV1';
var archiveMonths=[['01','Gennaio'],['02','Febbraio'],['03','Marzo'],['04','Aprile'],['05','Maggio'],['06','Giugno'],['07','Luglio'],['08','Agosto'],['09','Settembre'],['10','Ottobre'],['11','Novembre'],['12','Dicembre']];
var archiveClosedDepartments={};
function archiveCurrentYear(){return new Date().getFullYear()}
function archiveCurrentMonthKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function archiveSelectedMonth(){return localStorage.getItem(archiveSelectedMonthStoreName)||archiveCurrentMonthKey()}
function archiveMode(){return localStorage.getItem(archiveModeStoreName)||'monthly'}
function saveArchiveSelectedMonth(value){localStorage.setItem(archiveSelectedMonthStoreName,value)}
function saveArchiveMode(value){localStorage.setItem(archiveModeStoreName,value)}
function archivePublishedWeeks(){try{return JSON.parse(localStorage.getItem(publishedWeeksStoreName)||'{}')}catch(e){return{}}}
function archiveDaysInMonth(monthKey){var p=monthKey.split('-');return new Date(Number(p[0]),Number(p[1]),0).getDate()}
function archiveDateKey(monthKey,day){return monthKey+'-'+String(day).padStart(2,'0')}
function archiveDayName(monthKey,day){var d=new Date(archiveDateKey(monthKey,day));return ['Dom','Lun','Mar','Mer','Gio','Ven','Sab'][d.getDay()]}
function archiveWeekForDate(dateValue){var d=new Date(dateValue);var day=d.getDay()||7;d.setDate(d.getDate()+4-day);var y=new Date(d.getFullYear(),0,1);var w=Math.ceil((((d-y)/86400000)+1)/7);return d.getFullYear()+'-W'+String(w).padStart(2,'0')}
function archiveDayKey(dateValue){var d=new Date(dateValue);return days[(d.getDay()+6)%7][0]}
function archiveShiftFor(person,depKey,dateValue){var week=archiveWeekForDate(dateValue);var day=archiveDayKey(dateValue);var data=(typeof allData==='object'&&allData[week])?allData[week]:{};return data[cellKey(depKey,person,day)]||''}
function archivePresenceCode(value){var v=String(value||'').trim().toLowerCase();if(!v)return'';if(v==='riposo'||v==='festa'||v==='off')return'F';if(v==='fer'||v==='ferie')return'Fer';if(v==='mal'||v==='malattia')return'MAL';if(v==='ass'||v==='assenza')return'Ass';if(v.indexOf('rit')>-1)return'Rit';return'P'}
function archiveCellClass(code){if(code==='P')return'archive-p';if(code==='F')return'archive-f';if(code==='Fer')return'archive-fer';if(code==='MAL')return'archive-mal';if(code==='Ass')return'archive-ass';if(code==='Rit')return'archive-rit';return'archive-empty'}
function archiveSelectMonth(value,label){saveArchiveSelectedMonth(value);renderArchiveMonths();renderArchiveContent();var status=document.getElementById('archiveStatus');if(status)status.textContent='Mese selezionato: '+label+' '+value.slice(0,4)}
function renderArchiveMonths(){var root=document.getElementById('archiveMonths');if(!root)return;var year=archiveCurrentYear();var current=archiveCurrentMonthKey();var selected=archiveSelectedMonth();root.innerHTML='';archiveMonths.forEach(function(month){var value=year+'-'+month[0];var btn=document.createElement('button');btn.type='button';btn.className='archive-month-btn';if(value===current)btn.classList.add('is-current-month');if(value===selected)btn.classList.add('is-selected-month');btn.textContent=month[1];btn.addEventListener('click',function(){archiveSelectMonth(value,month[1])});root.appendChild(btn)})}
function renderArchiveLegend(){var root=document.getElementById('archiveLegend');if(!root)return;root.innerHTML='<span class="archive-legend-item archive-p">P Presenza</span><span class="archive-legend-item archive-f">F Festa</span><span class="archive-legend-item archive-fer">Fer Ferie</span><span class="archive-legend-item archive-mal">MAL Malattia</span><span class="archive-legend-item archive-ass">Ass Assenza</span><span class="archive-legend-item archive-rit">Rit Ritardo</span>'}
function renderMonthlyArchive(){var root=document.getElementById('archiveGrid');if(!root)return;var month=archiveSelectedMonth();var total=archiveDaysInMonth(month);var html='<div class="archive-table-card"><div class="archive-table-title"><strong>Grafico mensile presenze staff</strong><span>'+month+'</span></div><div class="archive-scroll"><table class="archive-presence-table"><thead><tr><th class="archive-staff-head">Staff</th>';for(var d=1;d<=total;d++){html+='<th><strong>'+d+'</strong><small>'+archiveDayName(month,d)+'</small></th>'}html+='</tr></thead><tbody>';departments.forEach(function(dep){var closed=archiveClosedDepartments[dep.key];html+='<tr class="archive-section-row '+(closed?'is-closed':'')+'"><td colspan="'+(total+1)+'"><button class="archive-section-toggle" type="button" data-archive-dep="'+dep.key+'"><span>'+dep.title+'</span><small>'+dep.people.length+' persone</small></button></td></tr>';dep.people.forEach(function(person){html+='<tr class="archive-person-row '+(closed?'is-hidden':'')+'" data-archive-person-dep="'+dep.key+'"><th>'+person+'</th>';for(var d=1;d<=total;d++){var date=archiveDateKey(month,d);var code=archivePresenceCode(archiveShiftFor(person,dep.key,date));html+='<td class="'+archiveCellClass(code)+'">'+code+'</td>'}html+='</tr>'})});html+='</tbody></table></div></div>';root.innerHTML=html}
function renderWeeklyArchive(){var root=document.getElementById('archiveGrid');if(!root)return;var published=archivePublishedWeeks();var keys=Object.keys(published).sort().reverse();if(!keys.length){root.innerHTML='<div class="archive-weekly-box"><strong>Archivio settimanale</strong><p>Nessuna settimana pubblicata nel registro.</p></div>';return}var html='<div class="archive-weekly-box"><strong>Archivio settimanale</strong><p>Settimane registrate e consultabili.</p><div class="archive-week-list">';keys.forEach(function(week){var item=published[week]||{};var count=0;if(item.data){Object.keys(item.data).forEach(function(k){if(item.data[k]&&item.data[k]!=='Riposo')count++})}html+='<button class="archive-week-card" type="button" data-archive-week="'+week+'"><span>'+week+'</span><small>Turni compilati: '+count+'</small><b>Registrata</b></button>'});html+='</div></div>';root.innerHTML=html}
function renderArchiveContent(){renderArchiveLegend();var mode=archiveMode();var monthly=document.getElementById('archiveMonthlyModeBtn');var weekly=document.getElementById('archiveWeeklyModeBtn');if(monthly)monthly.classList.toggle('active',mode==='monthly');if(weekly)weekly.classList.toggle('active',mode==='weekly');if(mode==='weekly'){renderWeeklyArchive()}else{renderMonthlyArchive()}}
function setArchiveMode(mode){saveArchiveMode(mode);renderArchiveContent()}
function setupArchivePage(){renderArchiveMonths();renderArchiveContent();var monthly=document.getElementById('archiveMonthlyModeBtn');var weekly=document.getElementById('archiveWeeklyModeBtn');if(monthly)monthly.addEventListener('click',function(){setArchiveMode('monthly')});if(weekly)weekly.addEventListener('click',function(){setArchiveMode('weekly')});var grid=document.getElementById('archiveGrid');if(grid)grid.addEventListener('click',function(event){var btn=event.target.closest('.archive-section-toggle');if(btn){var key=btn.dataset.archiveDep;archiveClosedDepartments[key]=!archiveClosedDepartments[key];renderArchiveContent();return}var weekBtn=event.target.closest('.archive-week-card');if(weekBtn){alert('Settimana registrata: '+weekBtn.dataset.archiveWeek)}})}
window.openMonthlyArchive=function(){setArchiveMode('monthly');goArchiveView()};
window.openWeeklyArchive=function(){setArchiveMode('weekly');goArchiveView()};
function goArchiveView(){document.querySelectorAll('.view').forEach(function(v){v.classList.remove('active-view')});var view=document.getElementById('archivioView');if(view)view.classList.add('active-view')}
setupArchivePage();
