function dataBackupPayload(){return{createdAt:new Date().toISOString(),turni:JSON.parse(localStorage.getItem('capriBluAppTurniByWeekV1')||'{}'),settimana:localStorage.getItem('capriBluAppCurrentWeekV1')||'',richieste:JSON.parse(localStorage.getItem('capriBluAppRequestsV1')||'[]'),mensile:JSON.parse(localStorage.getItem('capriBluAppPublishedMonthlyWeeksV1')||'{}'),reparti:JSON.parse(localStorage.getItem('capriBluAppDepartmentOpenV1')||'{}'),archivio:localStorage.getItem('capriBluAppArchiveSelectedMonthV1')||''}}
function weeklyPublishPayload(){var full=dataBackupPayload();var week=full.settimana;var weekData=week&&full.turni[week]?full.turni[week]:{};return{createdAt:new Date().toISOString(),type:'settimanale',settimana:week,turni:weekData,richieste:full.richieste}}
function monthlyPublishPayload(){var full=dataBackupPayload();var d=new Date();var month=String(d.getFullYear())+'-'+String(d.getMonth()+1).padStart(2,'0');return{createdAt:new Date().toISOString(),type:'mensile',mese:month,settimane:full.mensile,richieste:full.richieste}}
function applyDataBackup(data){if(!data||typeof data!=='object')throw new Error('Formato dati non valido');localStorage.setItem('capriBluAppTurniByWeekV1',JSON.stringify(data.turni||{}));localStorage.setItem('capriBluAppCurrentWeekV1',data.settimana||'');localStorage.setItem('capriBluAppRequestsV1',JSON.stringify(data.richieste||[]));localStorage.setItem('capriBluAppPublishedMonthlyWeeksV1',JSON.stringify(data.mensile||{}));localStorage.setItem('capriBluAppDepartmentOpenV1',JSON.stringify(data.reparti||{}));localStorage.setItem('capriBluAppArchiveSelectedMonthV1',data.archivio||'')}
function setLocalOk(text){var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(official){official.textContent='Solo locale';official.classList.remove('is-dirty')}if(save){save.textContent=text||'Salvato locale';save.classList.remove('is-dirty')}}
function downloadJsonFile(filename,payload){var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});var url=URL.createObjectURL(blob);var link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)}
function saveDataToGitHub(manual){localStorage.setItem('capriBluAppLastAdminBackupV1',JSON.stringify(dataBackupPayload()));setLocalOk('Backup locale pronto');if(manual)downloadJsonFile('current-data.json',dataBackupPayload());return Promise.resolve(true)}
function publishWeeklyOnline(manual){var payload=weeklyPublishPayload();localStorage.setItem('capriBluAppPublishedWeeklyCurrentV1',JSON.stringify(payload));setLocalOk('Settimanale locale pronto');if(manual)downloadJsonFile('current-week.json',payload);return Promise.resolve(true)}
function publishMonthlyOnline(manual){var payload=monthlyPublishPayload();localStorage.setItem('capriBluAppPublishedMonthlyCurrentV1',JSON.stringify(payload));setLocalOk('Mensile locale pronto');if(manual)downloadJsonFile('current-month.json',payload);return Promise.resolve(true)}
function loadDataFromGitHub(){hideMainMenu&&hideMainMenu();fetch('../data/current-data.json?ts='+Date.now()).then(function(response){if(!response.ok)throw new Error('File dati non trovato');return response.json()}).then(function(data){if(!confirm('Caricare il backup admin da GitHub? I dati locali saranno sostituiti.'))return;applyDataBackup(data);setLocalOk('Backup caricato');alert('Backup admin caricato. La pagina verrà aggiornata.');window.location.reload()}).catch(function(){alert('Non riesco a caricare data/current-data.json da GitHub.')})}
function formatAutoSaveTime(seconds){var m=Math.floor(seconds/60);var s=seconds%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function runLocalAutoSave(){localStorage.setItem('capriBluAppLastAutoSaveV1',JSON.stringify(dataBackupPayload()));localStorage.setItem('capriBluAppLastAutoSaveAtV1',new Date().toISOString());var label=document.getElementById('autoSaveCountdown');if(label)label.textContent='Auto save ok';setLocalOk('Auto salvato locale')}
function setupAutoSaveCountdown(){var total=210;var left=total;var label=document.getElementById('autoSaveCountdown');function tick(){if(label)label.textContent='Auto save '+formatAutoSaveTime(left);left--;if(left<0){runLocalAutoSave();left=total}}tick();setInterval(tick,1000)}
function publishWeeklyShifts(){if(!confirm('Preparare i turni settimanali e scaricare il file current-week.json?'))return;if(typeof sendWeekToMonthly==='function')sendWeekToMonthly();publishWeeklyOnline(true).then(function(){alert('Settimanale preparato in locale. Per ora caricalo manualmente in data/settimanale/current-week.json.')})}
function publishMonthlyData(){if(!confirm('Preparare i dati mensili e scaricare il file current-month.json?'))return;publishMonthlyOnline(true).then(function(){alert('Mensile preparato in locale. Per ora caricalo manualmente in data/mensile/current-month.json.')})}
setupAutoSaveCountdown();
