var githubRepoName='CapriBlu/Turni-Capri-Blu-Sorrento';
var githubDataPath='data/current-data.json';
var githubBranch='main';
function dataBackupPayload(){return{createdAt:new Date().toISOString(),turni:JSON.parse(localStorage.getItem('capriBluAppTurniByWeekV1')||'{}'),settimana:localStorage.getItem('capriBluAppCurrentWeekV1')||'',richieste:JSON.parse(localStorage.getItem('capriBluAppRequestsV1')||'[]'),mensile:JSON.parse(localStorage.getItem('capriBluAppPublishedMonthlyWeeksV1')||'{}'),reparti:JSON.parse(localStorage.getItem('capriBluAppDepartmentOpenV1')||'{}'),archivio:localStorage.getItem('capriBluAppArchiveSelectedMonthV1')||''}}
function applyDataBackup(data){if(!data||typeof data!=='object')throw new Error('Formato dati non valido');localStorage.setItem('capriBluAppTurniByWeekV1',JSON.stringify(data.turni||{}));localStorage.setItem('capriBluAppCurrentWeekV1',data.settimana||'');localStorage.setItem('capriBluAppRequestsV1',JSON.stringify(data.richieste||[]));localStorage.setItem('capriBluAppPublishedMonthlyWeeksV1',JSON.stringify(data.mensile||{}));localStorage.setItem('capriBluAppDepartmentOpenV1',JSON.stringify(data.reparti||{}));localStorage.setItem('capriBluAppArchiveSelectedMonthV1',data.archivio||'')}
function githubToken(){return sessionStorage.getItem('capriBluGitHubTokenV1')||''}
function setGitHubToken(token){sessionStorage.setItem('capriBluGitHubTokenV1',token)}
function clearDirtyState(text){var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(official){official.textContent='GitHub ok';official.classList.remove('is-dirty')}if(save){save.textContent=text||'Sync GitHub ok';save.classList.remove('is-dirty')}}
function isDirty(){var official=document.getElementById('officialDataStatus');return official&&official.classList.contains('is-dirty')}
function encodeBase64Utf8(value){return btoa(unescape(encodeURIComponent(value)))}
function saveDataToGitHub(manual){var token=githubToken();var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(!token){if(manual&&typeof showAdminTokenPanel==='function')showAdminTokenPanel();if(save)save.textContent='Token mancante';return Promise.resolve(false)}if(official)official.textContent='Sync GitHub...';return fetch('https://api.github.com/repos/'+githubRepoName+'/contents/'+githubDataPath+'?ref='+githubBranch,{headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json'}}).then(function(response){if(!response.ok)throw new Error('SHA non trovato');return response.json()}).then(function(file){var body={message:'Aggiorna dati turni da app admin',content:encodeBase64Utf8(JSON.stringify(dataBackupPayload(),null,2)),sha:file.sha,branch:githubBranch};return fetch('https://api.github.com/repos/'+githubRepoName+'/contents/'+githubDataPath,{method:'PUT',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify(body)})}).then(function(response){if(!response.ok)throw new Error('Sync GitHub fallito');clearDirtyState('GitHub salvato');return true}).catch(function(){if(official){official.textContent='Errore GitHub';official.classList.add('is-dirty')}if(save)save.textContent='Controlla token';return false})}
function loadDataFromGitHub(){hideMainMenu&&hideMainMenu();fetch('../data/current-data.json?ts='+Date.now()).then(function(response){if(!response.ok)throw new Error('File dati non trovato');return response.json()}).then(function(data){if(!confirm('Scaricare i dati correnti da GitHub? I dati locali saranno sostituiti.'))return;applyDataBackup(data);clearDirtyState('Nessuna modifica');alert('Dati scaricati da GitHub. La pagina verrà aggiornata.');window.location.reload()}).catch(function(){alert('Non riesco a scaricare data/current-data.json da GitHub. Controlla che il file sia online.')})}
function formatAutoSaveTime(seconds){var m=Math.floor(seconds/60);var s=seconds%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function runLocalAutoSave(){localStorage.setItem('capriBluAppLastAutoSaveV1',JSON.stringify(dataBackupPayload()));localStorage.setItem('capriBluAppLastAutoSaveAtV1',new Date().toISOString());var label=document.getElementById('autoSaveCountdown');if(label)label.textContent='Auto save ok';var save=document.getElementById('saveStatus');if(save)save.textContent='Auto salvato locale';if(githubToken()&&isDirty())saveDataToGitHub(false)}
function setupAutoSaveCountdown(){var total=210;var left=total;var label=document.getElementById('autoSaveCountdown');function tick(){if(label)label.textContent='Auto save '+formatAutoSaveTime(left);left--;if(left<0){runLocalAutoSave();left=total}}tick();setInterval(tick,1000)}
function showAdminTokenPanel(){var panel=document.getElementById('adminTokenPanel');if(panel){panel.classList.add('open');panel.setAttribute('aria-hidden','false')}}
function hideAdminTokenPanel(){var panel=document.getElementById('adminTokenPanel');if(panel){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}}
function setupAdminTokenPanel(){var input=document.getElementById('adminTokenInput');var save=document.getElementById('saveAdminTokenBtn');var skip=document.getElementById('skipAdminTokenBtn');if(!githubToken())showAdminTokenPanel();if(save)save.addEventListener('click',function(){var token=(input&&input.value?input.value:'').trim();if(!token){alert('Inserisci un token valido');return}setGitHubToken(token);hideAdminTokenPanel();var official=document.getElementById('officialDataStatus');if(official)official.textContent='Token attivo';saveDataToGitHub(false)});if(skip)skip.addEventListener('click',function(){hideAdminTokenPanel()})}
function publishWeeklyShifts(){if(!confirm('Pubblicare i turni settimanali e aggiornare la pagina sola lettura?'))return;if(typeof sendWeekToMonthly==='function')sendWeekToMonthly();saveDataToGitHub(true).then(function(ok){if(ok){alert('Turni pubblicati. Ora puoi avvisare lo staff da Notifiche.')}})}
setupAdminTokenPanel();
setupAutoSaveCountdown();
