var githubRepoName='CapriBlu/Turni-Capri-Blu-Sorrento';
var githubDataPath='data/current-data.json';
var weeklyDataPath='data/settimanale/current-week.json';
var monthlyDataPath='data/mensile/current-month.json';
var githubBranch='main';
function dataBackupPayload(){return{createdAt:new Date().toISOString(),turni:JSON.parse(localStorage.getItem('capriBluAppTurniByWeekV1')||'{}'),settimana:localStorage.getItem('capriBluAppCurrentWeekV1')||'',richieste:JSON.parse(localStorage.getItem('capriBluAppRequestsV1')||'[]'),mensile:JSON.parse(localStorage.getItem('capriBluAppPublishedMonthlyWeeksV1')||'{}'),reparti:JSON.parse(localStorage.getItem('capriBluAppDepartmentOpenV1')||'{}'),archivio:localStorage.getItem('capriBluAppArchiveSelectedMonthV1')||''}}
function weeklyPublishPayload(){var full=dataBackupPayload();var week=full.settimana;var weekData=week&&full.turni[week]?full.turni[week]:{};return{createdAt:new Date().toISOString(),type:'settimanale',settimana:week,turni:weekData,richieste:full.richieste}}
function monthlyPublishPayload(){var full=dataBackupPayload();var d=new Date();var month=String(d.getFullYear())+'-'+String(d.getMonth()+1).padStart(2,'0');return{createdAt:new Date().toISOString(),type:'mensile',mese:month,settimane:full.mensile,richieste:full.richieste}}
function applyDataBackup(data){if(!data||typeof data!=='object')throw new Error('Formato dati non valido');localStorage.setItem('capriBluAppTurniByWeekV1',JSON.stringify(data.turni||{}));localStorage.setItem('capriBluAppCurrentWeekV1',data.settimana||'');localStorage.setItem('capriBluAppRequestsV1',JSON.stringify(data.richieste||[]));localStorage.setItem('capriBluAppPublishedMonthlyWeeksV1',JSON.stringify(data.mensile||{}));localStorage.setItem('capriBluAppDepartmentOpenV1',JSON.stringify(data.reparti||{}));localStorage.setItem('capriBluAppArchiveSelectedMonthV1',data.archivio||'')}
function githubToken(){return sessionStorage.getItem('capriBluGitHubTokenV1')||''}
function setGitHubToken(token){sessionStorage.setItem('capriBluGitHubTokenV1',token)}
function clearDirtyState(text){var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(official){official.textContent='GitHub ok';official.classList.remove('is-dirty')}if(save){save.textContent=text||'Sync GitHub ok';save.classList.remove('is-dirty')}}
function isDirty(){var official=document.getElementById('officialDataStatus');return official&&official.classList.contains('is-dirty')}
function encodeBase64Utf8(value){return btoa(unescape(encodeURIComponent(value)))}
function setGitHubError(text){var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(official){official.textContent='Errore GitHub';official.classList.add('is-dirty')}if(save)save.textContent=text||'Controlla token'}
function savePayloadToGitHub(path,payload,message,manual){var token=githubToken();var official=document.getElementById('officialDataStatus');if(!token){if(manual&&typeof showAdminTokenPanel==='function')showAdminTokenPanel();setGitHubError('Token mancante');return Promise.resolve(false)}if(official)official.textContent='Sync GitHub...';return fetch('https://api.github.com/repos/'+githubRepoName+'/contents/'+path+'?ref='+githubBranch,{headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json'}}).then(function(response){if(response.status===401)throw new Error('Token non valido');if(response.status===403)throw new Error('Permessi token');if(!response.ok)throw new Error('File dati non accessibile');return response.json()}).then(function(file){var body={message:message,content:encodeBase64Utf8(JSON.stringify(payload,null,2)),sha:file.sha,branch:githubBranch};return fetch('https://api.github.com/repos/'+githubRepoName+'/contents/'+path,{method:'PUT',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify(body)})}).then(function(response){if(response.status===401)throw new Error('Token non valido');if(response.status===403)throw new Error('Permessi token');if(!response.ok)throw new Error('Sync GitHub fallito');clearDirtyState('GitHub salvato');return true}).catch(function(error){setGitHubError(error.message);if(manual)alert('Pubblicazione non riuscita: '+error.message+'. Controlla token e permessi Contents Read/Write.');return false})}
function saveDataToGitHub(manual){return savePayloadToGitHub(githubDataPath,dataBackupPayload(),'Aggiorna dati turni da app admin',manual)}
function publishWeeklyOnline(manual){return savePayloadToGitHub(weeklyDataPath,weeklyPublishPayload(),'Pubblica turni settimanali',manual)}
function publishMonthlyOnline(manual){return savePayloadToGitHub(monthlyDataPath,monthlyPublishPayload(),'Pubblica dati mensili',manual)}
function loadDataFromGitHub(){hideMainMenu&&hideMainMenu();fetch('../data/current-data.json?ts='+Date.now()).then(function(response){if(!response.ok)throw new Error('File dati non trovato');return response.json()}).then(function(data){if(!confirm('Scaricare i dati correnti da GitHub? I dati locali saranno sostituiti.'))return;applyDataBackup(data);clearDirtyState('Nessuna modifica');alert('Dati scaricati da GitHub. La pagina verrà aggiornata.');window.location.reload()}).catch(function(){alert('Non riesco a scaricare data/current-data.json da GitHub. Controlla che il file sia online.')})}
function formatAutoSaveTime(seconds){var m=Math.floor(seconds/60);var s=seconds%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function runLocalAutoSave(){localStorage.setItem('capriBluAppLastAutoSaveV1',JSON.stringify(dataBackupPayload()));localStorage.setItem('capriBluAppLastAutoSaveAtV1',new Date().toISOString());var label=document.getElementById('autoSaveCountdown');if(label)label.textContent='Auto save ok';var save=document.getElementById('saveStatus');if(save)save.textContent='Auto salvato locale';if(githubToken()&&isDirty())saveDataToGitHub(false)}
function setupAutoSaveCountdown(){var total=210;var left=total;var label=document.getElementById('autoSaveCountdown');function tick(){if(label)label.textContent='Auto save '+formatAutoSaveTime(left);left--;if(left<0){runLocalAutoSave();left=total}}tick();setInterval(tick,1000)}
function showAdminTokenPanel(){var panel=document.getElementById('adminTokenPanel');if(panel){panel.classList.add('open');panel.setAttribute('aria-hidden','false')}}
function hideAdminTokenPanel(){var panel=document.getElementById('adminTokenPanel');if(panel){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}}
function setupAdminTokenPanel(){var input=document.getElementById('adminTokenInput');var save=document.getElementById('saveAdminTokenBtn');var skip=document.getElementById('skipAdminTokenBtn');if(!githubToken())showAdminTokenPanel();if(save)save.addEventListener('click',function(){var token=(input&&input.value?input.value:'').trim();if(!token){alert('Inserisci un token valido');return}setGitHubToken(token);hideAdminTokenPanel();var official=document.getElementById('officialDataStatus');if(official)official.textContent='Token attivo';saveDataToGitHub(false)});if(skip)skip.addEventListener('click',function(){hideAdminTokenPanel()})}
function publishWeeklyShifts(){if(!confirm('Inviare i turni settimanali alla pagina sola lettura?'))return;if(typeof sendWeekToMonthly==='function')sendWeekToMonthly();publishWeeklyOnline(true).then(function(ok){if(ok){alert('Turni settimanali pubblicati online. La pagina sola lettura può visualizzarli.')}else{alert('Turni salvati localmente, ma NON pubblicati nel settimanale online.')}})}
function publishMonthlyData(){if(!confirm('Inviare i dati mensili online?'))return;publishMonthlyOnline(true).then(function(ok){if(ok){alert('Dati mensili pubblicati online.')}})}
setupAdminTokenPanel();
setupAutoSaveCountdown();
