var gitRepo='CapriBlu/Turni-Capri-Blu-Sorrento';
var gitBranch='main';
function gitToken(){var t=prompt('Token GitHub solo per questo caricamento. Non viene salvato.');return t?t.trim():''}
function b64(value){return btoa(unescape(encodeURIComponent(value)))}
function gitStatus(text,error){var a=document.getElementById('officialDataStatus');var b=document.getElementById('saveStatus');if(a){a.textContent=error?'Errore GitHub':'GitHub ok';a.classList.toggle('is-dirty',!!error)}if(b)b.textContent=text}
function uploadJsonToGitHub(path,payload,message){var token=gitToken();if(!token){gitStatus('Token mancante',true);return Promise.resolve(false)}gitStatus('Caricamento GitHub...');var api='https://api.github.com/repos/'+gitRepo+'/contents/'+path;return fetch(api+'?ref='+gitBranch,{headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json'}}).then(function(r){if(r.status===401)throw new Error('Token non valido');if(r.status===403)throw new Error('Permessi token');if(!r.ok)throw new Error('File non accessibile');return r.json()}).then(function(file){return fetch(api,{method:'PUT',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify({message:message,content:b64(JSON.stringify(payload,null,2)),sha:file.sha,branch:gitBranch})})}).then(function(r){if(r.status===401)throw new Error('Token non valido');if(r.status===403)throw new Error('Permessi token');if(!r.ok)throw new Error('Upload fallito');gitStatus('Caricato su GitHub');return true}).catch(function(e){gitStatus(e.message,true);alert('Caricamento GitHub non riuscito: '+e.message);return false})}
function uploadBackupToGitHub(){return uploadJsonToGitHub('data/app/current-data.json',dataBackupPayload(),'Aggiorna backup app turni')}
function uploadWeeklyToGitHub(){return uploadJsonToGitHub('data/registry/weekly/current-week.json',weeklyPublishPayload(),'Pubblica registro settimanale')}
function uploadMonthlyToGitHub(){return uploadJsonToGitHub('data/registry/monthly/current-month.json',monthlyPublishPayload(),'Pubblica registro mensile')}
function downloadBackupFromGitHub(){fetch('../data/app/current-data.json?ts='+Date.now()).then(function(r){if(!r.ok)throw new Error('Backup non trovato');return r.json()}).then(function(data){if(!confirm('Scaricare il backup da GitHub? I dati locali saranno sostituiti.'))return;applyDataBackup(data);gitStatus('Backup scaricato da GitHub');alert('Backup scaricato. La pagina verrà aggiornata.');window.location.reload()}).catch(function(e){alert('Scaricamento backup non riuscito: '+e.message)})}
