var readAdminEmail='admin@capriblusorrento.it';
var readDays=[['lunedi','Lun'],['martedi','Mar'],['mercoledi','Mer'],['giovedi','Gio'],['venerdi','Ven'],['sabato','Sab'],['domenica','Dom']];
var readDepartments=[{key:'sala',title:'Sala',people:['Pawel','Rafaele','Gaetano','Rose','Shan','Brendon','Vittorio','Dylan','Lorenzo','Sabbit','Annachiara','Natalia','Carmine']},{key:'pizzeria',title:'Pizzeria',people:['LUCA','MARIO','IGOR','CRISTIAN','PIETRO']},{key:'cucina',title:'Cucina / Lavaggio',people:['ANTONINO','Lavapiatti','AJITH','DIEGO','Saja']}];
function readCellKey(dep,person,day){return dep+'_'+person+'_'+day}
function readShiftClass(value){var v=String(value||'').toLowerCase();if(!v)return'';if(v==='riposo')return' is-rest';if(v.indexOf('/')>-1||v.indexOf(':')>-1)return' is-special';return' is-filled'}
function showStatus(text,type){var box=document.getElementById('readStatus');if(!box)return;box.textContent=text;box.style.background=type==='error'?'#ffe1e1':'#fff4cf';box.style.color=type==='error'?'#970000':'#775000'}
function readLocalRequests(){try{return JSON.parse(localStorage.getItem('capriBluReadRequestsV1')||'[]')}catch(e){return[]}}
function saveLocalRequests(items){localStorage.setItem('capriBluReadRequestsV1',JSON.stringify(items))}
function dayFromDate(date){var d=new Date(date);return readDays[(d.getDay()+6)%7][0]}
function requestStatusFor(person,day){var items=readLocalRequests();var found=items.find(function(item){return item.name===person&&dayFromDate(item.date)===day});return found?found.status:''}
function renderReadOnly(data){var root=document.getElementById('readSchedule');var label=document.getElementById('readWeekLabel');if(!root)return;var week=data&&data.settimana?data.settimana:'';var weekData=data&&data.turni?data.turni:{};if(label)label.textContent=week?'Settimana '+week:'Turni non ancora pubblicati';if(!week||!Object.keys(weekData).length){root.innerHTML='<div class="empty-box">Turni settimanali non ancora pubblicati.<br>Controlla più tardi oppure premi Aggiorna.</div>';return}var html='';readDepartments.forEach(function(dep){html+='<section class="department-card"><button class="department-title" type="button" data-read-dep="'+dep.key+'"><span>'+dep.title+'</span></button><div class="department-body">';dep.people.forEach(function(person){html+='<div class="employee-row"><div class="employee-name">'+person+'</div><div class="days-grid">';readDays.forEach(function(day){var value=weekData[readCellKey(dep.key,person,day[0])]||'';var status=requestStatusFor(person,day[0]);var cls=readShiftClass(value)+(status==='pending'?' request-pending':status==='approvata'?' request-approved':'');html+='<div class="shift-cell'+cls+'"><span class="shift-day">'+day[1]+'</span><span class="shift-value">'+(value||'-')+'</span></div>'});html+='</div></div>'});html+='</div></section>'});root.innerHTML=html;setupDepartmentToggles();renderLocalRequests()}
function setupDepartmentToggles(){document.querySelectorAll('[data-read-dep]').forEach(function(btn){btn.addEventListener('click',function(){btn.closest('.department-card').classList.toggle('is-closed')})})}
function sendReadRequest(){var name=document.getElementById('requestNameInput');var email=document.getElementById('requestEmailInput');var type=document.getElementById('requestTypeInput');var date=document.getElementById('requestDateInput');var note=document.getElementById('requestNoteInput');var item={id:Date.now(),name:(name.value||'').trim(),email:(email.value||'').trim(),type:type.value,date:date.value,note:note.value,status:'pending'};if(!item.name||!item.date){alert('Inserisci nome e giorno richiesta.');return}var items=readLocalRequests();items.push(item);saveLocalRequests(items);renderLocalRequests();var subject='Richiesta staff '+item.name+' - '+item.date;var body='Nome: '+item.name+'\nEmail risposta: '+item.email+'\nTipo: '+item.type+'\nGiorno: '+item.date+'\nNota: '+item.note+'\n\nStato: in attesa di approvazione';window.location.href='mailto:'+readAdminEmail+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)}
function renderLocalRequests(){var box=document.getElementById('localRequestsBox');if(!box)return;var items=readLocalRequests().slice().reverse();if(!items.length){box.innerHTML='';return}box.innerHTML=items.map(function(item){return'<div class="local-request-item '+item.status+'"><strong>'+item.name+'</strong> '+item.type+' - '+item.date+'<br><small>'+(item.status==='approvata'?'Approvata':'In attesa')+'</small></div>'}).join('')}
function loadReadOnly(){showStatus('Lettura settimanale da GitHub...');fetch('../data/settimanale/current-week.json?ts='+Date.now()).then(function(r){if(!r.ok)throw new Error('Dati non trovati');return r.json()}).then(function(data){renderReadOnly(data);showStatus('Dati settimanali aggiornati: '+new Date().toLocaleTimeString('it-IT'))}).catch(function(){showStatus('Non riesco a leggere il file settimanale da GitHub.','error')})}
var refresh=document.getElementById('refreshReadBtn');if(refresh)refresh.addEventListener('click',loadReadOnly);
var sendBtn=document.getElementById('sendRequestBtn');if(sendBtn)sendBtn.addEventListener('click',sendReadRequest);
loadReadOnly();
setInterval(loadReadOnly,180000);
