function dataBackupPayload(){return{createdAt:new Date().toISOString(),turni:JSON.parse(localStorage.getItem('capriBluAppTurniByWeekV1')||'{}'),settimana:localStorage.getItem('capriBluAppCurrentWeekV1')||'',richieste:JSON.parse(localStorage.getItem('capriBluAppRequestsV1')||'[]'),mensile:JSON.parse(localStorage.getItem('capriBluAppPublishedMonthlyWeeksV1')||'{}'),reparti:JSON.parse(localStorage.getItem('capriBluAppDepartmentOpenV1')||'{}'),archivio:localStorage.getItem('capriBluAppArchiveSelectedMonthV1')||''}}
function weeklyPublishPayload(){var full=dataBackupPayload();var week=full.settimana;return{createdAt:new Date().toISOString(),type:'settimanale',settimana:week,turni:week&&full.turni[week]?full.turni[week]:{},richieste:full.richieste}}
function monthlyPublishPayload(){var full=dataBackupPayload();var d=new Date();return{createdAt:new Date().toISOString(),type:'mensile',mese:d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'),settimane:full.mensile,richieste:full.richieste}}
function applyDataBackup(data){if(!data||typeof data!=='object')throw new Error('Formato dati non valido');localStorage.setItem('capriBluAppTurniByWeekV1',JSON.stringify(data.turni||{}));localStorage.setItem('capriBluAppCurrentWeekV1',data.settimana||'');localStorage.setItem('capriBluAppRequestsV1',JSON.stringify(data.richieste||[]));localStorage.setItem('capriBluAppPublishedMonthlyWeeksV1',JSON.stringify(data.mensile||{}));localStorage.setItem('capriBluAppDepartmentOpenV1',JSON.stringify(data.reparti||{}));localStorage.setItem('capriBluAppArchiveSelectedMonthV1',data.archivio||'')}
function setLocalOk(text){var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(official){official.textContent='Solo locale';official.classList.remove('is-dirty')}if(save){save.textContent=text||'Salvato locale';save.classList.remove('is-dirty')}}
function formatAutoSaveTime(seconds){var m=Math.floor(seconds/60);var s=seconds%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function runLocalAutoSave(){localStorage.setItem('capriBluAppLastAutoSaveV1',JSON.stringify(dataBackupPayload()));localStorage.setItem('capriBluAppLastAutoSaveAtV1',new Date().toISOString());var label=document.getElementById('autoSaveCountdown');if(label)label.textContent='Auto save ok';setLocalOk('Auto salvato locale')}
function setupAutoSaveCountdown(){var total=210;var left=total;var label=document.getElementById('autoSaveCountdown');function tick(){if(label)label.textContent='Auto save '+formatAutoSaveTime(left);left--;if(left<0){runLocalAutoSave();left=total}}tick();setInterval(tick,1000)}
setupAutoSaveCountdown();
