var weeklyRegistryPath='data/registry/weekly/current-week.json';
var monthlyRegistryPath='data/registry/monthly/current-month.json';
function dataBackupPayload(){return{createdAt:new Date().toISOString(),turni:JSON.parse(localStorage.getItem('capriBluAppTurniByWeekV1')||'{}'),settimana:localStorage.getItem('capriBluAppCurrentWeekV1')||'',richieste:JSON.parse(localStorage.getItem('capriBluAppRequestsV1')||'[]'),mensile:JSON.parse(localStorage.getItem('capriBluAppPublishedMonthlyWeeksV1')||'{}'),reparti:JSON.parse(localStorage.getItem('capriBluAppDepartmentOpenV1')||'{}'),archivio:localStorage.getItem('capriBluAppArchiveSelectedMonthV1')||''}}
function weeklyPublishPayload(){var full=dataBackupPayload();var week=full.settimana;return{createdAt:new Date().toISOString(),type:'settimanale',settimana:week,turni:week&&full.turni[week]?full.turni[week]:{},richieste:full.richieste}}
function monthlyPublishPayload(){var full=dataBackupPayload();var d=new Date();return{createdAt:new Date().toISOString(),type:'mensile',mese:d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'),settimane:full.mensile,richieste:full.richieste}}
function applyDataBackup(data){if(!data||typeof data!=='object')throw new Error('Formato dati non valido');localStorage.setItem('capriBluAppTurniByWeekV1',JSON.stringify(data.turni||{}));localStorage.setItem('capriBluAppCurrentWeekV1',data.settimana||'');localStorage.setItem('capriBluAppRequestsV1',JSON.stringify(data.richieste||[]));localStorage.setItem('capriBluAppPublishedMonthlyWeeksV1',JSON.stringify(data.mensile||{}));localStorage.setItem('capriBluAppDepartmentOpenV1',JSON.stringify(data.reparti||{}));localStorage.setItem('capriBluAppArchiveSelectedMonthV1',data.archivio||'')}
function setLocalOk(text){var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(official){official.textContent='Solo locale';official.classList.remove('is-dirty')}if(save){save.textContent=text||'Salvato locale';save.classList.remove('is-dirty')}}
function downloadJsonFile(filename,payload){var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});var url=URL.createObjectURL(blob);var link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)}
function saveDataToGitHub(manual){var payload=dataBackupPayload();localStorage.setItem('capriBluAppLastAdminBackupV1',JSON.stringify(payload));setLocalOk('Backup app locale pronto');if(manual)downloadJsonFile('current-data.json',payload);return Promise.resolve(true)}
function importBackupFromFile(){var input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.addEventListener('change',function(){var file=input.files&&input.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){try{var data=JSON.parse(String(reader.result||'{}'));if(!confirm('Caricare questo backup? I dati locali saranno sostituiti.'))return;applyDataBackup(data);setLocalOk('Backup importato');alert('Backup caricato. La pagina verrà aggiornata.');window.location.reload()}catch(e){alert('File backup non valido.')}};reader.readAsText(file)});input.click()}
function publishWeeklyOnline(manual){var payload=weeklyPublishPayload();localStorage.setItem('capriBluAppPublishedWeeklyCurrentV1',JSON.stringify(payload));setLocalOk('Registro settimanale pronto');if(manual)downloadJsonFile('current-week.json',payload);return Promise.resolve(true)}
function publishMonthlyOnline(manual){var payload=monthlyPublishPayload();localStorage.setItem('capriBluAppPublishedMonthlyCurrentV1',JSON.stringify(payload));setLocalOk('Registro mensile pronto');if(manual)downloadJsonFile('current-month.json',payload);return Promise.resolve(true)}
function fetchJsonWithFallback(paths,index){return fetch(paths[index]+'?ts='+Date.now()).then(function(r){if(!r.ok)throw new Error('no');return r.json()}).catch(function(e){if(index+1<paths.length)return fetchJsonWithFallback(paths,index+1);throw e})}
function loadDataFromGitHub(){hideMainMenu&&hideMainMenu();fetchJsonWithFallback(['../data/app/current-data.json','../data/current-data.json'],0).then(function(data){if(!confirm('Caricare il backup app? I dati locali saranno sostituiti.'))return;applyDataBackup(data);setLocalOk('Backup caricato');alert('Backup app caricato. La pagina verrà aggiornata.');window.location.reload()}).catch(function(){alert('Non riesco a caricare il backup app.')})}
function formatAutoSaveTime(seconds){var m=Math.floor(seconds/60);var s=seconds%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function runLocalAutoSave(){localStorage.setItem('capriBluAppLastAutoSaveV1',JSON.stringify(dataBackupPayload()));localStorage.setItem('capriBluAppLastAutoSaveAtV1',new Date().toISOString());var label=document.getElementById('autoSaveCountdown');if(label)label.textContent='Auto save ok';setLocalOk('Auto salvato locale')}
function setupAutoSaveCountdown(){var total=210;var left=total;var label=document.getElementById('autoSaveCountdown');function tick(){if(label)label.textContent='Auto save '+formatAutoSaveTime(left);left--;if(left<0){runLocalAutoSave();left=total}}tick();setInterval(tick,1000)}
function publishWeeklyShifts(){if(!confirm('Preparare il registro settimanale e scaricare current-week.json?'))return;if(typeof sendWeekToMonthly==='function')sendWeekToMonthly();publishWeeklyOnline(true).then(function(){alert('Registro settimanale preparato. Caricalo in '+weeklyRegistryPath+'.')})}
function publishMonthlyData(){if(!confirm('Preparare il registro mensile e scaricare current-month.json?'))return;publishMonthlyOnline(true).then(function(){alert('Registro mensile preparato. Caricalo in '+monthlyRegistryPath+'.')})}
setupAutoSaveCountdown();
