function updateMenuWeekLabel(){var label=document.getElementById('menuWeekLabel');var week=document.getElementById('weekInput');if(label&&week)label.textContent=week.value||'-'}
function showMainMenu(){cleanupMenuLabels();updateMenuWeekLabel();var panel=document.getElementById('mainMenuPanel');if(panel){panel.classList.add('open');panel.setAttribute('aria-hidden','false')}}
function hideMainMenu(){var panel=document.getElementById('mainMenuPanel');if(panel){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}}
function showViewByName(name){document.querySelectorAll('.view').forEach(function(view){view.classList.remove('active-view')});var target=document.getElementById(name+'View');if(target)target.classList.add('active-view')}
function goToView(name){showViewByName(name);hideMainMenu()}
function showLegend(){alert('Legenda turni:\n\nArancione lampeggiante = richiesta in attesa\nVerde respiro = richiesta approvata\nA, P, S = turni sala\nA/S, P/S, M/S = spezzato')}
function cleanupMenuLabels(){var top=document.getElementById('topSendMonthlyBtn');var w=document.getElementById('menuPublishWeeklyBtn');var m=document.getElementById('menuPublishMonthlyBtn');var up=document.getElementById('menuLoadDataBtn');var down=document.getElementById('menuDownloadDataBtn');if(top)top.textContent='Invia settimanale';if(w)w.textContent='Invia settimanale su GitHub';if(m)m.textContent='Invia mese su GitHub';if(up)up.textContent='Carica backup su GitHub';if(down)down.textContent='Scarica backup da GitHub';['menuPrintBtn','menuMessagesBtn'].forEach(function(id){var el=document.getElementById(id);if(el)el.remove()})}
function loadGitHubUpload(callback){if(typeof uploadBackupToGitHub==='function'){callback();return}var script=document.createElement('script');script.src='github-upload.js?v=21';script.onload=callback;script.onerror=function(){alert('Non riesco a caricare il modulo GitHub.')};document.head.appendChild(script)}
function safePublishWeekly(){if(!confirm('Inviare il registro settimanale su GitHub?'))return;if(typeof sendWeekToMonthly==='function'){var ok=sendWeekToMonthly();if(!ok)return}loadGitHubUpload(function(){uploadWeeklyToGitHub().then(function(ok){if(ok)alert('Settimanale caricato su GitHub.')})})}
function safePublishMonthly(){if(!confirm('Inviare il registro mensile su GitHub?'))return;loadGitHubUpload(function(){uploadMonthlyToGitHub().then(function(ok){if(ok)alert('Mensile caricato su GitHub.')})})}
function setupMainMenu(){cleanupMenuLabels();var open=document.getElementById('mainMenuBtn');var close=document.getElementById('closeMainMenuBtn');var panel=document.getElementById('mainMenuPanel');if(open)open.addEventListener('click',showMainMenu);if(close)close.addEventListener('click',hideMainMenu);if(panel)panel.addEventListener('click',function(event){if(event.target===panel)hideMainMenu()});document.querySelectorAll('[data-menu-view]').forEach(function(button){button.addEventListener('click',function(){goToView(button.dataset.menuView)})});var copy=document.getElementById('menuCopyWeekBtn');if(copy)copy.addEventListener('click',function(){hideMainMenu();if(typeof copyPreviousWeekAction==='function')copyPreviousWeekAction()});var topSend=document.getElementById('topSendMonthlyBtn');if(topSend)topSend.addEventListener('click',safePublishWeekly);var publishWeek=document.getElementById('menuPublishWeeklyBtn');if(publishWeek)publishWeek.addEventListener('click',function(){hideMainMenu();safePublishWeekly()});var publishMonth=document.getElementById('menuPublishMonthlyBtn');if(publishMonth)publishMonth.addEventListener('click',function(){hideMainMenu();safePublishMonthly()});var legend=document.getElementById('legendBtn');if(legend)legend.addEventListener('click',showLegend);var monthlyArchive=document.getElementById('menuArchiveMonthlyBtn');if(monthlyArchive)monthlyArchive.addEventListener('click',function(){hideMainMenu();if(typeof openMonthlyArchive==='function')openMonthlyArchive();else goToView('archivio')});var weeklyArchive=document.getElementById('menuWeeklyArchiveBtn');if(weeklyArchive)weeklyArchive.addEventListener('click',function(){hideMainMenu();if(typeof openWeeklyArchive==='function')openWeeklyArchive();else goToView('archivio')});var load=document.getElementById('menuLoadDataBtn');if(load)load.addEventListener('click',function(){hideMainMenu();loadGitHubUpload(function(){uploadBackupToGitHub().then(function(ok){if(ok)alert('Backup admin caricato su GitHub.')})})});var download=document.getElementById('menuDownloadDataBtn');if(download)download.addEventListener('click',function(){hideMainMenu();loadGitHubUpload(function(){downloadBackupFromGitHub()})});var wa=document.getElementById('menuNotifyWhatsappBtn');if(wa)wa.addEventListener('click',function(){hideMainMenu();if(typeof notifyWhatsapp==='function')notifyWhatsapp('pubblicazione')});var mail=document.getElementById('menuNotifyEmailBtn');if(mail)mail.addEventListener('click',function(){hideMainMenu();if(typeof notifyEmail==='function')notifyEmail('pubblicazione')});var week=document.getElementById('weekInput');if(week)week.addEventListener('change',updateMenuWeekLabel)}
setupMainMenu();
