function updateMenuWeekLabel(){var label=document.getElementById('menuWeekLabel');var week=document.getElementById('weekInput');if(label&&week)label.textContent=week.value||'-'}
function showMainMenu(){updateMenuWeekLabel();var panel=document.getElementById('mainMenuPanel');if(panel){panel.classList.add('open');panel.setAttribute('aria-hidden','false')}}
function hideMainMenu(){var panel=document.getElementById('mainMenuPanel');if(panel){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}}
function showViewByName(name){document.querySelectorAll('.view').forEach(function(view){view.classList.remove('active-view')});var target=document.getElementById(name+'View');if(target)target.classList.add('active-view')}
function goToView(name){showViewByName(name);hideMainMenu()}
function showLegend(){alert('Legenda turni:\n\nVerde = Riposo / disponibile\nA, P, S = turni sala\nA/S, P/S, M/S = spezzato\nGiallo = turno speciale o orario personalizzato\nRichiesta = richiesta approvata collegata al giorno')}
function dataBackupPayload(){return{createdAt:new Date().toISOString(),turni:JSON.parse(localStorage.getItem('capriBluAppTurniByWeekV1')||'{}'),settimana:localStorage.getItem('capriBluAppCurrentWeekV1')||'',richieste:JSON.parse(localStorage.getItem('capriBluAppRequestsV1')||'[]'),mensile:JSON.parse(localStorage.getItem('capriBluAppPublishedMonthlyWeeksV1')||'{}'),reparti:JSON.parse(localStorage.getItem('capriBluAppDepartmentOpenV1')||'{}'),archivio:localStorage.getItem('capriBluAppArchiveSelectedMonthV1')||''}}
function applyDataBackup(data){if(!data||typeof data!=='object')throw new Error('Formato dati non valido');localStorage.setItem('capriBluAppTurniByWeekV1',JSON.stringify(data.turni||{}));localStorage.setItem('capriBluAppCurrentWeekV1',data.settimana||'');localStorage.setItem('capriBluAppRequestsV1',JSON.stringify(data.richieste||[]));localStorage.setItem('capriBluAppPublishedMonthlyWeeksV1',JSON.stringify(data.mensile||{}));localStorage.setItem('capriBluAppDepartmentOpenV1',JSON.stringify(data.reparti||{}));localStorage.setItem('capriBluAppArchiveSelectedMonthV1',data.archivio||'')}
function loadDataFromGitHub(){hideMainMenu();fetch('../data/current-data.json?ts='+Date.now()).then(function(response){if(!response.ok)throw new Error('File dati non trovato');return response.json()}).then(function(data){if(!confirm('Scaricare i dati correnti da GitHub? I dati locali saranno sostituiti.'))return;applyDataBackup(data);var official=document.getElementById('officialDataStatus');var save=document.getElementById('saveStatus');if(official){official.textContent='Dati ok';official.classList.remove('is-dirty')}if(save){save.textContent='Nessuna modifica';save.classList.remove('is-dirty')}alert('Dati scaricati da GitHub. La pagina verrà aggiornata.');window.location.reload()}).catch(function(){alert('Non riesco a scaricare data/current-data.json da GitHub. Controlla che il file sia online.')})}
function formatAutoSaveTime(seconds){var m=Math.floor(seconds/60);var s=seconds%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function runLocalAutoSave(){localStorage.setItem('capriBluAppLastAutoSaveV1',JSON.stringify(dataBackupPayload()));localStorage.setItem('capriBluAppLastAutoSaveAtV1',new Date().toISOString());var label=document.getElementById('autoSaveCountdown');if(label)label.textContent='Auto save ok';var save=document.getElementById('saveStatus');if(save)save.textContent='Auto salvato locale'}
function setupAutoSaveCountdown(){var total=210;var left=total;var label=document.getElementById('autoSaveCountdown');function tick(){if(label)label.textContent='Auto save '+formatAutoSaveTime(left);left--;if(left<0){runLocalAutoSave();left=total}}tick();setInterval(tick,1000)}
function setupMainMenu(){var open=document.getElementById('mainMenuBtn');var close=document.getElementById('closeMainMenuBtn');var panel=document.getElementById('mainMenuPanel');if(open)open.addEventListener('click',showMainMenu);if(close)close.addEventListener('click',hideMainMenu);if(panel)panel.addEventListener('click',function(event){if(event.target===panel)hideMainMenu()});document.querySelectorAll('[data-menu-view]').forEach(function(button){button.addEventListener('click',function(){goToView(button.dataset.menuView)})});var copy=document.getElementById('menuCopyWeekBtn');if(copy)copy.addEventListener('click',function(){hideMainMenu();if(typeof copyPreviousWeekAction==='function')copyPreviousWeekAction()});var topSend=document.getElementById('topSendMonthlyBtn');if(topSend)topSend.addEventListener('click',function(){if(typeof sendWeekToMonthly==='function')sendWeekToMonthly()});var legend=document.getElementById('legendBtn');if(legend)legend.addEventListener('click',showLegend);var monthlyArchive=document.getElementById('menuArchiveMonthlyBtn');if(monthlyArchive)monthlyArchive.addEventListener('click',function(){hideMainMenu();if(typeof openMonthlyArchive==='function')openMonthlyArchive();else goToView('archivio')});var weeklyArchive=document.getElementById('menuWeeklyArchiveBtn');if(weeklyArchive)weeklyArchive.addEventListener('click',function(){hideMainMenu();if(typeof openWeeklyArchive==='function')openWeeklyArchive();else goToView('archivio')});var load=document.getElementById('menuLoadDataBtn');if(load)load.addEventListener('click',function(){hideMainMenu();alert('Carica dati su GitHub sarà collegato al salvataggio online sicuro.')});var download=document.getElementById('menuDownloadDataBtn');if(download)download.addEventListener('click',loadDataFromGitHub);var print=document.getElementById('menuPrintBtn');if(print)print.addEventListener('click',function(){hideMainMenu();window.print()});var messages=document.getElementById('menuMessagesBtn');if(messages)messages.addEventListener('click',function(){hideMainMenu();alert('Messaggi personale in preparazione')});var week=document.getElementById('weekInput');if(week)week.addEventListener('change',updateMenuWeekLabel);setupAutoSaveCountdown()}
setupMainMenu();
