var settingsStoreName='capriBluAppDepartmentAdminsV1';
var defaultAdmins={adminGenerale:'Pawel.petruk@hotmail.com',reparti:{sala:'Pawel.petruk@hotmail.com',pizzeria:'Pawel.petruk@hotmail.com',cucina:'Pawel.petruk@hotmail.com'}};
function readSettings(){try{var saved=JSON.parse(localStorage.getItem(settingsStoreName)||'null');return saved||defaultAdmins}catch(e){return defaultAdmins}}
function saveSettings(data){localStorage.setItem(settingsStoreName,JSON.stringify(data));if(typeof markLocalChanges==='function')markLocalChanges('Settings salvati')}
function settingsInputValue(id){var el=document.getElementById(id);return el?(el.value||'').trim():''}
function renderSettings(){var data=readSettings();var general=document.getElementById('settingAdminGeneral');var sala=document.getElementById('settingAdminSala');var pizzeria=document.getElementById('settingAdminPizzeria');var cucina=document.getElementById('settingAdminCucina');if(general)general.value=data.adminGenerale||defaultAdmins.adminGenerale;if(sala)sala.value=(data.reparti&&data.reparti.sala)||data.adminGenerale||defaultAdmins.adminGenerale;if(pizzeria)pizzeria.value=(data.reparti&&data.reparti.pizzeria)||data.adminGenerale||defaultAdmins.adminGenerale;if(cucina)cucina.value=(data.reparti&&data.reparti.cucina)||data.adminGenerale||defaultAdmins.adminGenerale}
function downloadSettings(){var data=readSettings();var blob=new Blob([JSON.stringify({createdAt:new Date().toISOString(),adminGenerale:data.adminGenerale,reparti:data.reparti},null,2)],{type:'application/json'});var url=URL.createObjectURL(blob);var link=document.createElement('a');link.href=url;link.download='admins.json';link.click();URL.revokeObjectURL(url)}
function saveSettingsFromForm(){var general=settingsInputValue('settingAdminGeneral')||defaultAdmins.adminGenerale;var data={adminGenerale:general,reparti:{sala:settingsInputValue('settingAdminSala')||general,pizzeria:settingsInputValue('settingAdminPizzeria')||general,cucina:settingsInputValue('settingAdminCucina')||general}};saveSettings(data);renderSettings();alert('Settings admin salvati localmente.')}
function setupSettings(){renderSettings();var save=document.getElementById('saveSettingsBtn');var download=document.getElementById('downloadSettingsBtn');if(save)save.addEventListener('click',saveSettingsFromForm);if(download)download.addEventListener('click',downloadSettings)}
setupSettings();
